basePath: /
definitions:
  models.ErrorResponse:
    properties:
      is_success:
        type: boolean
      message:
        type: string
    type: object
  models.SuccessResponse:
    properties:
      is_success:
        type: boolean
      message:
        type: string
    type: object
info:
  contact: {}
  description: API untuk mengirim email HTML melalui SMTP.
  title: SMTP Email Sender API
  version: "1.0"
paths:
  /send-email:
    post:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: Sending HTML email using SMTP with access code validation
      parameters:
      - default: your_access_code_here
        description: Access Code
        in: formData
        name: accessCode
        required: true
        type: string
      - default: your-email@example.com
        description: Email Sender
        in: formData
        name: emailSender
        required: true
        type: string
      - default: your_app_password
        description: Sender Password
        in: formData
        name: senderPassword
        required: true
        type: string
      - default: recipient@example.com
        description: Email Recipient
        in: formData
        name: emailRecipient
        required: true
        type: string
      - default: Testing Email
        description: Subject
        in: formData
        name: subject
        required: true
        type: string
      - default: <html><body><h1>Hello World</h1></body></html>
        description: HTML Body
        in: formData
        name: body
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Send HTML emails
      tags:
      - email
swagger: "2.0"
